# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do 
  desc "Generate release version"
  lane :release do |options|
    gradle(task: "clean")
    gradle(
        task: "assemble",
        build_type: "Release",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deployRelease do
    gradle(task: "clean")
    gradle(
        task: "assemble",
        build_type: "Release"
    )
    upload_to_play_store
  end
end
